### ISSUE TITLE
Open rules in new tab

### ISSUE THREAD

**Issue by padawin** [padawin/three2fifteen#8]
The rules link currently opens the page in the current browser tab, making people confused whether they can click "back" to go back in the game or in the lobby (yes they can).

To remove confusion, the rules link should have a `target="_blank"` attribute.

**Comment by JAYESH8011** [comment]
Hey, I am a beginner in this issue can you suggest me how to get started

**Comment by padawin** [comment]
You can install the app following the instructions in the `README.md`. For this issue, you do not need to have a database.
Once your application is running, you can modify the templates and refresh the page to see the effects.

The HTML templates are in the directory `web/templates`.

Let me know if you have more questions.

**Comment by padawin** [comment]
Thanks for it! I merged the branch.
